# coding: utf-8

"""
    Consumer Data Standards

    API sets created by the Australian Consumer Data Standards to meet the needs of the Consumer Data Right  # noqa: E501

    OpenAPI spec version: 1.1.1
    Contact: cdr-data61@csiro.au
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.banking_transaction_detail_extended_data_x2p101_payload import BankingTransactionDetailExtendedDataX2p101Payload  # noqa: E501
from swagger_client.rest import ApiException


class TestBankingTransactionDetailExtendedDataX2p101Payload(unittest.TestCase):
    """BankingTransactionDetailExtendedDataX2p101Payload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBankingTransactionDetailExtendedDataX2p101Payload(self):
        """Test BankingTransactionDetailExtendedDataX2p101Payload"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.banking_transaction_detail_extended_data_x2p101_payload.BankingTransactionDetailExtendedDataX2p101Payload()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
