# coding: utf-8

"""
    Consumer Data Standards

    API sets created by the Australian Consumer Data Standards to meet the needs of the Consumer Data Right  # noqa: E501

    OpenAPI spec version: 1.1.1
    Contact: cdr-data61@csiro.au
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.response_common_customer import ResponseCommonCustomer  # noqa: E501
from swagger_client.rest import ApiException


class TestResponseCommonCustomer(unittest.TestCase):
    """ResponseCommonCustomer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResponseCommonCustomer(self):
        """Test ResponseCommonCustomer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.response_common_customer.ResponseCommonCustomer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
