# coding: utf-8

"""
    Consumer Data Standards

    API sets created by the Australian Consumer Data Standards to meet the needs of the Consumer Data Right  # noqa: E501

    OpenAPI spec version: 1.1.1
    Contact: cdr-data61@csiro.au
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.products_api import ProductsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestProductsApi(unittest.TestCase):
    """ProductsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.products_api.ProductsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_product_detail(self):
        """Test case for get_product_detail

        Get Product Detail  # noqa: E501
        """
        pass

    def test_list_products(self):
        """Test case for list_products

        Get Products  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
