# coding: utf-8

"""
    Consumer Data Standards

    API sets created by the Australian Consumer Data Standards to meet the needs of the Consumer Data Right  # noqa: E501

    OpenAPI spec version: 1.1.1
    Contact: cdr-data61@csiro.au
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.banking_product_v2 import BankingProductV2  # noqa: E501
from swagger_client.rest import ApiException


class TestBankingProductV2(unittest.TestCase):
    """BankingProductV2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBankingProductV2(self):
        """Test BankingProductV2"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.banking_product_v2.BankingProductV2()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
