# coding: utf-8

"""
    Consumer Data Standards

    API sets created by the Australian Consumer Data Standards to meet the needs of the Consumer Data Right  # noqa: E501

    OpenAPI spec version: 1.1.1
    Contact: cdr-data61@csiro.au
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.common_api import CommonApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCommonApi(unittest.TestCase):
    """CommonApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.common_api.CommonApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_customer(self):
        """Test case for get_customer

        Get Customer  # noqa: E501
        """
        pass

    def test_get_customer_detail(self):
        """Test case for get_customer_detail

        Get Customer Detail  # noqa: E501
        """
        pass

    def test_get_outages(self):
        """Test case for get_outages

        Get Outages  # noqa: E501
        """
        pass

    def test_get_status(self):
        """Test case for get_status

        Get Status  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
